/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Equipo;

import Controlador.*;
import Modelo.DataBase.Conexion;

/**
 *
 * @author Lozano
 */
public class FrameEquipo extends javax.swing.JFrame {

    /**
     * Creates new form FrameRegistrar
     */
    public FrameEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new EstablecerFondo("/imagenes/fondo1.jpg");
        registrarEquipos = new javax.swing.JButton();
        modificarEquipos = new javax.swing.JButton();
        buscarEquipos1 = new javax.swing.JButton();
        buscarEquipos2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(555, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));

        jPanel2.setBackground(new java.awt.Color(28, 11, 25));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 239, 244));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Módulo de Equipos");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        registrarEquipos.setBackground(new java.awt.Color(255, 255, 255));
        registrarEquipos.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        registrarEquipos.setText("Registrar Equipo ");
        registrarEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registrarEquipos.setFocusPainted(false);
        registrarEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarEquiposMouseClicked(evt);
            }
        });
        registrarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEquiposActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(62, 258, 0, 297);
        jPanel1.add(registrarEquipos, gridBagConstraints);

        modificarEquipos.setBackground(new java.awt.Color(255, 255, 255));
        modificarEquipos.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        modificarEquipos.setText("Modificar Equipo");
        modificarEquipos.setFocusPainted(false);
        modificarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEquiposActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 258, 0, 0);
        jPanel1.add(modificarEquipos, gridBagConstraints);

        buscarEquipos1.setBackground(new java.awt.Color(255, 255, 255));
        buscarEquipos1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        buscarEquipos1.setText("Eliminar Equipos");
        buscarEquipos1.setFocusPainted(false);
        buscarEquipos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipos1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 258, 37, 0);
        jPanel1.add(buscarEquipos1, gridBagConstraints);

        buscarEquipos2.setBackground(new java.awt.Color(255, 255, 255));
        buscarEquipos2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        buscarEquipos2.setText("Listar Equipos");
        buscarEquipos2.setFocusPainted(false);
        buscarEquipos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipos2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 258, 0, 297);
        jPanel1.add(buscarEquipos2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEquiposActionPerformed
        FrameRegistrar equipo = new FrameRegistrar();
        equipo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarEquiposActionPerformed

    private void registrarEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEquiposMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarEquiposMouseClicked

    private void modificarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEquiposActionPerformed
        boolean validar = true;
        FrameBuscar buscar = new FrameBuscar(validar);
        buscar.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_modificarEquiposActionPerformed

    private void buscarEquipos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipos1ActionPerformed
        FrameEliminar eliminar = new FrameEliminar();
        eliminar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarEquipos1ActionPerformed

    private void buscarEquipos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipos2ActionPerformed

        FrameBuscar buscar = new FrameBuscar();
        buscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarEquipos2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarEquipos1;
    private javax.swing.JButton buscarEquipos2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modificarEquipos;
    private javax.swing.JButton registrarEquipos;
    // End of variables declaration//GEN-END:variables
}
