/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Equipo;

/**
 *
 * @author Lozano
 */
public class FrameEquipo extends javax.swing.JFrame {

    /**
     * Creates new form FrameRegistrar
     */
    public FrameEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelEp1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buscarEquipos1 = new javax.swing.JButton();
        registrarEquipos = new javax.swing.JButton();
        modificarEquipos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelEp1.setBackground(new java.awt.Color(0, 102, 204));
        panelEp1.setName(""); // NOI18N
        panelEp1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("HP Simplified", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Módulo de Equipos");
        jPanel1.add(jLabel1);

        panelEp1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        buscarEquipos1.setBackground(new java.awt.Color(255, 255, 255));
        buscarEquipos1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        buscarEquipos1.setText("Listar Equipos");
        buscarEquipos1.setFocusPainted(false);
        buscarEquipos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipos1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        jPanel2.add(buscarEquipos1, gridBagConstraints);

        registrarEquipos.setBackground(new java.awt.Color(255, 255, 255));
        registrarEquipos.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        registrarEquipos.setText("Registrar Equipo ");
        registrarEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        registrarEquipos.setFocusPainted(false);
        registrarEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarEquiposMouseClicked(evt);
            }
        });
        registrarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEquiposActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        jPanel2.add(registrarEquipos, gridBagConstraints);

        modificarEquipos.setBackground(new java.awt.Color(255, 255, 255));
        modificarEquipos.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        modificarEquipos.setText("Modificar Equipo");
        modificarEquipos.setFocusPainted(false);
        modificarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarEquiposActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        jPanel2.add(modificarEquipos, gridBagConstraints);

        panelEp1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEp1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEp1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEquiposActionPerformed
        FrameRegistrar equipo =new FrameRegistrar();
        equipo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrarEquiposActionPerformed

    private void registrarEquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarEquiposMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarEquiposMouseClicked

    private void modificarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarEquiposActionPerformed
        boolean validar=true;
        FrameBuscar buscar=new FrameBuscar(validar);
        buscar.setVisible(true);
        
    }//GEN-LAST:event_modificarEquiposActionPerformed

    private void buscarEquipos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipos1ActionPerformed
        BuscarEquipo buscar= new BuscarEquipo();
        buscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarEquipos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarEquipos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton modificarEquipos;
    private javax.swing.JPanel panelEp1;
    private javax.swing.JButton registrarEquipos;
    // End of variables declaration//GEN-END:variables
}
